### ISSUE TITLE
HTTPS call is not working

### ISSUE THREAD

**Issue by VandeperreMaarten** [ahmetb/gke-letsencrypt#18]
I followed this tutorial, but the last step is not working (serving through HTTPS).
The secret is created, I can access it on HTTP but not on HTTPS.
Can you guide me to the fix?

this is the output of the describe ingress:

Name:             helloweb
Namespace:        default
Address:          35.190.68.173
Default backend:  helloweb-backend:8080 (10.32.0.17:8080)
TLS:
  dogs-com-tls terminates app-solidair-vlaanderen.com
Rules:
  Host                         Path  Backends
  ----                         ----  --------
  app-solidair-vlaanderen.com
                               /.well-known/acme-challenge/Q8kcFSZ0ZUJO58xZyVbK6s-cJIWu-EgwPcDd8NFyoXQ   cm-acme-http-solver-mhqnf:8089 (<none>)
Annotations:
  url-map:          k8s-um-default-helloweb--17a833239f9491d9
  backends:         {"k8s-be-30819--17a833239f9491d9":"Unknown","k8s-be-32482--17a833239f9491d9":"HEALTHY"}
  forwarding-rule:  k8s-fw-default-helloweb--17a833239f9491d9
  target-proxy:     k8s-tp-default-helloweb--17a833239f9491d9
Events:
  Type     Reason  Age                From                     Message
  ----     ------  ----               ----                     -------
  Normal   ADD     45m                loadbalancer-controller  default/helloweb
  Normal   CREATE  44m                loadbalancer-controller  ip: 35.190.68.173
  Warning  Sync    7m (x22 over 28m)  loadbalancer-controller  Error during sync: error while evaluating the ingress spec: could not find service "default/cm-acme-http-solver-mhqnf"

**Comment by ahmetb** [comment]
I’d say delete everything and follow again. Looks like a timing issue happened and the ACME challenge solver was not cleaned up from ingress. 

If the issue persists, file a bug to cert-manager repository.

**Comment by johnbalvin** [comment]
Did you solve it? I'm facing the same problem

**Comment by VandeperreMaarten** [comment]
It is solved now.
I recreated the ingress and changed 3 things:
-1: I added " certmanager.k8s.io/acme-http01-edit-in-place: "true" " to the annotations
-2: I changed the secret from "www-dogs-com-tls" to "dogs-com-tls" as it was defined without "www"
-3: I added a health path (i.e. readiness probe) on the deployment

optional: if you want to force HTTPS, you can add 2 other annotations. 
Now it's working like a charm. Many thanks to the creators, maintainers!!!!

my ingress config:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: helloweb-ip
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app: hello
spec:
  rules:
    - host: app-solidair-vlaanderen.com
      http:
        paths:
        - path: /*
          backend:
            serviceName: helloweb-backend
            servicePort: 8080
  tls:
  - secretName: dogs-com-tls
    hosts:
    - app-solidair-vlaanderen.com
```

and service + deployment (changed the image to a keycloak one):

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: gcr.io/solidair-vlaanderen-204118/sv-security:0.0.1
        ports:
          - name: http
            containerPort: 8080
          - name: management
            containerPort: 9090
          - name: jgroups-tcp
            containerPort: 7600
          - name: jgroups-tcp-fd
            containerPort: 57600
          - name: jgroups-udp
            containerPort: 55200
            protocol: UDP
          - name: jgroups-udp-mc
            containerPort: 45688
            protocol: UDP
          - name: jgroups-udp-fd
            containerPort: 54200
            protocol: UDP
          - name: modcluster
            containerPort: 23364
          - name: modcluster-udp
            containerPort: 23365
            protocol: UDP
          - name: txn-recovery-ev
            containerPort: 4712
          - name: txn-status-mgr
            containerPort: 4713
        readinessProbe:
          httpGet:
            path: /auth/
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-backend
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
```
